# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-22 20:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=511)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
